services:
  - type: web
    name: sales-story
    runtime: static
    buildCommand: "echo 'no build needed'"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /salesphilosophy
        destination: /index.html
      - type: rewrite
        source: /playbooks
        destination: /index.html
      - type: rewrite
        source: /customer-stories
        destination: /index.html
      - type: rewrite
        source: /background
        destination: /index.html
